global using System.Text;
global using CommandLine;
global using AdGuardHomeConnector.GitHubAction.Extensions;
global using AdGuardHomeConnector.GitHubAction.Gateways;
global using AdGuardHomeConnector.GitHubAction.Services;
global using AdGuardHomeConnector.GitHubAction.Models;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using static CommandLine.Parser;